//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by FBAPECPP.RC
//
#define ID_HELP_ABOUT                   100
#define ID_FILE_EXIT                    101
#define IDC_MAIN_OK                     103
#define IDT_FBAPE_MAIN                  104
#define IDC_VOL_ANALOG                  105
#define IDC_VOL_SDCARD                  106
#define IDC_VOL_SPDIF                   107
#define IDC_VOL_MAIN                    108
#define IDC_VOL_SUB                     109
#define IDC_VOL_ULTRANET                110
#define IDC_EQ_TYPE                     130
#define IDC_EQ_FREQ                     131
#define IDC_EQ_Q                        132
#define IDC_EQ_GAIN                     133
#define IDC_LBL_FREQ                    134
#define IDC_LBL_Q                       135
#define IDC_EQ_SET1                     136
#define IDC_EQ_SET2                     137
#define IDC_EQ_SET3                     138
#define IDC_EQ_SET4                     139
#define IDC_EQ_SET5                     140
#define IDC_COMP_THRESH                 141
#define IDC_COMP_RATIO                  142
#define IDC_COMP_MAKEUP                 143
#define IDC_COMP_ATTACK                 144
#define IDC_COMP_HOLD                   145
#define IDC_COMP_RELEASE                146
#define IDC_LBL_THRESH                  147
#define IDC_LBL_ATTACK                  148
#define IDC_LBL_HOLD                    149
#define IDC_LBL_RELEASE                 150
#define IDC_SYNCSOURCE                  151
#define IDC_SAMPLERATE                  152
#define IDC_COMPORT                     153
#define IDC_CONNECT                     154
#define IDC_DISCONNECT                  155
#define IDC_LOWCUT                      156
#define IDC_HIGHCUT                     157
#define IDC_LBL_LOWCUT                  158
#define IDC_LBL_HIGHCUT                 159
#define IDC_PLAY                        160
#define IDC_PAUSE                       161
#define IDC_STOP                        162
#define IDC_FILENAME                    163
#define IDC_LOAD                        164
#define IDC_LOOP                        165
#define IDC_VOL_ANALOG_DB               166
#define IDC_VOL_SDCARD_DB               167
#define IDC_VOL_SPDIF_DB                168
#define IDC_VOL_MAIN_DB                 169
#define IDC_VOL_SUB_DB                  170
#define IDC_LBL_GAIN                    171
#define IDC_BAUDRATE                    172
#define IDC_GATE_ATTACK                 200
#define IDC_GATE_HOLD                   201
#define IDC_GATE_RANGE                  202
#define IDC_GATE_RELEASE                203
#define IDC_GATE_THRESH                 204
#define IDC_LBL_GATTACK                 205
#define IDC_LBL_GHOLD                   206
#define IDC_LBL_GRANGE                  207
#define IDC_LBL_GRELEASE                208
#define IDC_LBL_GTHRESH                 209
#define ID_APPICON                      1000
#define IDI_APPICON                     1000
#define IDC_VOLUME_MAIN                 1006
#define IDC_VOLUME_SUB                  1007
#define IDC_COMPORTS                    1009
#define IDC_EDIT                        1010
#define IDC_LISTBOX                     1011
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         103
#define _APS_NEXT_CONTROL_VALUE         1012
#define _APS_NEXT_SYMED_VALUE           162
#endif
#endif
